### ISSUE TITLE
withe balance of real scenes

### ISSUE THREAD

**Issue by AAAeray** [deborahLevy130/seathru_NeRF#11]
Hi DeborahLevy,
Thanks for sharing your great work! I want to know that in your real captured data, images have been white balance corrected when training the NeRF, so what's the white balance parameters in underwater scenes, how do you choose those parameters. And whether the performance would be worse if I don't do that when there is no such WB parameters. Is there any suggestions when training my real data.
Thanks a looot!

**Comment by deborahLevy130** [comment]
Hello,
I calculated the wb parameters as follow:
```
imagesPath = fullfile('F:\matan\dng\pngImages\');
imageList = dir(imagesPath);
[ imageNum] = length(imageList);
scale = [913, 1370];
for imageIdx = 1:imageNum-3

   imageVec(:,:,:,imageIdx) = im2double(imresize(imread(fullfile(imageList(imageIdx+2).folder,imageList(imageIdx+2).name)),scale));
  
end

wb = max(imageVec,[],[1,2,4]);
wb = prctile(imageVec, 99.8,[ 1,2,4]);


for imgIdx = 1:imageNum-3
    currImage = imageVec(:,:,:,imgIdx)./wb;
end
```
basically, I calculated for each color channel the 0.02 upper precentage of all the pixels in the set as the wb parameters.
It can also work without wb, but in order to work with colmap and get the poses of the cameras, you need to use it.
As for our own data, it's important to work on raw data, where the images are linear.

**Comment by AAAeray** [comment]
Hi DeborahLevy,
Thanks for your guidance. Can I ask for the raw data  in your paper. I am struging in such a project and there are so few data like this on the internert.

**Comment by CarlBhy** [comment]
Hi DeborahLevy,

I apologize for the interruption. I'm uncertain if now is the appropriate time to reach out to you regarding obtaining the raw data from your paper. Lately, I have been dedicating my efforts to underwater image enhancement, and I believe the SeaThru-NeRF dataset would be highly valuable for conducting experimental evaluations. 
If it is feasible, I kindly request your assistance in accessing the dataset. For further communication, you can reach me at bihengyue@gmail.com. Once again, thank you very much.

Thank you for your attention.

Best regards,
Hengyue

**Comment by deborahLevy130** [comment]
> Hi DeborahLevy, Thanks for your guidance. Can I ask for the raw data in your paper. I am struging in such a project and there are so few data like this on the internert. If it is possible, this is my email [xiazeng9-c@my.cityu.edu.hk](mailto:xiazeng9-c@my.cityu.edu.hk) Thanks a lot!

Hello, here is a [link](https://campushaifaac-my.sharepoint.com/:f:/g/personal/dstein09_campus_haifa_ac_il/Eu3gbf7h9FhAlN08nfq_KFIBKmqH3K5NDkZ-UqVr0urG1w?e=NIjDdI)

**Comment by ShaohuaL** [comment]
> > Hi DeborahLevy, Thanks for your guidance. Can I ask for the raw data in your paper. I am struging in such a project and there are so few data like this on the internert. If it is possible, this is my email [xiazeng9-c@my.cityu.edu.hk](mailto:xiazeng9-c@my.cityu.edu.hk) Thanks a lot!
> 
> Hello, here is a [link](https://campushaifaac-my.sharepoint.com/:f:/g/personal/dstein09_campus_haifa_ac_il/Eu3gbf7h9FhAlN08nfq_KFIBKmqH3K5NDkZ-UqVr0urG1w?e=NIjDdI)


Hello, I'm very sorry, but I didn't manage to access the uploaded raw dataset in time. It seems that the link has expired. Could you please re-upload it? @deborahLevy130
