### ISSUE TITLE
Some questions about rendering my own dataset.

### ISSUE THREAD

**Issue by guwenxiang1** [deborahLevy130/seathru_NeRF#12]
Hi, I selected 20 images from the images in the folder as my dataset. 
![1](https://github.com/deborahLevy130/seathru_NeRF/assets/43127637/b20b8713-46bf-4d52-924e-a23d298f7738)

Then, I used COLMAP to estimate the camera poses and generated the poses_bounds file using LLFF. After that, I started the training process. The generated images during training seemed to be fine, but the quality of the rendered images after training is very poor, as shown in the image below:
![2](https://github.com/deborahLevy130/seathru_NeRF/assets/43127637/e2dd1843-a536-4c08-b7ea-0bb42a670377)

Is it because the variation in viewpoints in the training set is too small?Do you know the reason behind this? I'm looking forward to your response.

**Comment by Wingerllyyy** [comment]
Have you found the reason yet?
