### ISSUE TITLE
Some problem about table2 in this paper

### ISSUE THREAD

**Issue by SakuBorder** [deborahLevy130/seathru_NeRF#13]
Hello, may I ask what you mean by the validation set used in Table 2 in your paper? I replicated your code and found that the results of the eval are not very good under the same iterations, but the indicators during its training process are close to what you proposed. Was the validation set you mentioned here used during the training process?

**Comment by deborahLevy130** [comment]
Hello, 
The validation set was used during training only for visualization during the training process. It wasn't use to decide when to stop the training.
If you want you can share your results/code and I'll try to see how I can help.

**Comment by SakuBorder** [comment]
> Hello, The validation set was used during training only for visualization during the training process. It wasn't use to decide when to stop the training. If you want you can share your results/code and I'll try to see how I can help.

Thank you for your reply. I have another question: The "Red sea" mentioned in your article, which dataset does it refer to? Is it a combination of "IUI3-RedSea" and "JapaneseGradens-RedSea"? And are the red squares manually selected?

**Comment by deborahLevy130** [comment]
Hello, 
The red squares were manually selected once and then applied on the rest of the results of the same set. 
The Red sea in the article is JapaneseGradens-RedSea

**Comment by SakuBorder** [comment]
> Hello, The red squares were manually selected once and then applied on the rest of the results of the same set. The Red sea in the article is JapaneseGradens-RedSea

Thanks, i got it
