### ISSUE TITLE
About equation 22

### ISSUE THREAD

**Issue by lucky9-cyou** [deborahLevy130/seathru_NeRF#21]
Could you please provide the detailed derivation process for equation 22?

**Comment by deborahLevy130** [comment]
Hello, 
Does [this](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Levy_SeaThru-NeRF_Neural_Radiance_CVPR_2023_supplemental.pdf) helps?

**Comment by lucky9-cyou** [comment]
I'll check it. Thanks a lot.
