### ISSUE TITLE
jax version

### ISSUE THREAD

**Issue by WHUTzmy** [deborahLevy130/seathru_NeRF#3]
Hello, I installed jax==0.3.23 and jaxlib==0.3.22+cuda11.cudnn82 library as per requirement.txt,  but at runtime I got AttributeError: module 'jax.tree_util' has no attribute 'register_pytree_with_keys_class', do you know what's the reason?

**Comment by deborahLevy130** [comment]
Did it work out for you with #4 response of cinamon123?

**Comment by WHUTzmy** [comment]
My problem has been solved, thank you very much！
