### ISSUE TITLE
About data images_wb

### ISSUE THREAD

**Issue by cinamon123** [deborahLevy130/seathru_NeRF#4]
Hi! Thanks for your adorable contributions！😀 
I have reproduced ideal results on your data, following your advice.  However, I found the images_wb you provided seems more greyer than those in your paper and on your website.  Is there any pre-process that I missed?
![image](https://github.com/deborahLevy130/seathru_NeRF/assets/104305930/341ca682-4a2f-4be6-bdc3-e45e94fd6586)

**Comment by WHUTzmy** [comment]
Hello, May I ask you a question? I installed jax==0.3.23 and jaxlib==0.3.22+cuda11.cudnn82 library as per requirement.txt, but at runtime I got AttributeError: module 'jax.tree_util' has no attribute 'register_pytree_with_keys_class', my cuda version is 11.3, too. If I upgrade jaxlib to 0.4.10+cuda11.cudnn86, I will not have this problem, but I will get bus error, do you have any idea? thanks!!!

**Comment by cinamon123** [comment]
I didn't met this. My CUDA is 11.7, and use `pip install --upgrade jax==0.3.23 jaxlib==0.3.22+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`.

**Comment by WHUTzmy** [comment]
thank you!

**Comment by deborahLevy130** [comment]
Hi,
It's a good question about the images.
The images in the data set are linear images, i.e. RAW images that were only demosaiced.
When we process our images we use the camera pipeline by Karaimer and Brown. their code and documentation can be found [here]( https://karaimer.github.io/camera-pipeline/ ). We take RAW images apply the pipeline until stage 4 and wb and resize them, and those are the images in the images_wb folder. When we render our images we apply on them the camera pipeline from stage 5 until the end-we call it photofinish. And hence the difference between your results and the paper. 
I will publish soon a script and instructions on how to use the camera pipeline for photofinish.

**Comment by cinamon123** [comment]
Thank you for your answer, which solved a lot of my confusion!😀

**Comment by cinamon123** [comment]
Thank you for your answer, which solved a lot of my confusion!😀

**Comment by SakuBorder** [comment]
> Hi, It's a good question about the images. The images in the data set are linear images, i.e. RAW images that were only demosaiced. When we process our images we use the camera pipeline by Karaimer and Brown. their code and documentation can be found [here](https://karaimer.github.io/camera-pipeline/). We take RAW images apply the pipeline until stage 4 and wb and resize them, and those are the images in the images_wb folder. When we render our images we apply on them the camera pipeline from stage 5 until the end-we call it photofinish. And hence the difference between your results and the paper. I will publish soon a script and instructions on how to use the camera pipeline for photofinish.
Hello, I would like to ask what is meant here by "When we render our images we apply on them the camera pipeline from stage 5 until the end-we call it photofinish"? Is it the nerf input?
