### ISSUE TITLE
Agisoft depth

### ISSUE THREAD

**Issue by cinamon123** [deborahLevy130/seathru_NeRF#6]
I read your paper in detail these days, and am very interested in it. I noticed you used Agisoft's depth as your reference. I want to know the dark-purple part of depth map is the massive artefacts or the mask.
![image](https://github.com/deborahLevy130/seathru_NeRF/assets/104305930/6c22e4a0-f287-4974-9222-eedbfba28d65)
Thank you for your patience!🥰

**Comment by deborahLevy130** [comment]
Hi,
Thank you for your interest in my work :)
The purple part is where Agisoft was not able to predict the depth. We didn't use masks.

**Comment by cinamon123** [comment]
OK, got it! Thank you so much🎉
