### ISSUE TITLE
Obtaining Underwater Simulation Images

### ISSUE THREAD

**Issue by keniee** [deborahLevy130/seathru_NeRF#8]
Hi there,

I'm attempting to follow the paper and utilise Eq.7 to simulate my own underwater scenes and recreate the fern dataset. Would you be able to shed some light on the solve for VD, VB, and z and how it fits into the simulation from RGB images? Is there a code base that could be at all possible shared?

Cheers

**Comment by deborahLevy130** [comment]
Hi,
I will publish our code for the simulation soon. Meanwhile [here](https://campushaifaac-my.sharepoint.com/:f:/g/personal/dstein09_campus_haifa_ac_il/En1jAWulaI9KsKzaybkYXZAB88FTu9QS0HgvnmFyDPHalQ?e=5KB7mz) you can find the simulated images we used for the paper. 
When you run the seathru-nerf with the simulation you can use the same configuration as the real-world scenes, but you need to change the extra_samples flag to True and change the factor to 4.

**Comment by MMMazart** [comment]
Hi，
I'm alos trying to simulate  an underwater scenes and recreate the fern dataset. I have a question to ask you：
Use the depth map predicted by mipnerf360 to simulate the scene. In its configuration file, is that forward_facing = true, near=0, far=1? So the range of this depth map is between 0-1?
Looking forward to your reply, thanks！

**Comment by MMMazart** [comment]
> Hi, I will publish our code for the simulation soon. Meanwhile [here](https://campushaifaac-my.sharepoint.com/:f:/g/personal/dstein09_campus_haifa_ac_il/En1jAWulaI9KsKzaybkYXZAB88FTu9QS0HgvnmFyDPHalQ?e=5KB7mz) you can find the simulated images we used for the paper. When you run the seathru-nerf with the simulation you can use the same configuration as the real-world scenes, but you need to change the extra_samples flag to True and change the factor to 4.

sss

**Comment by deborahLevy130** [comment]
Yes

**Comment by KFClpy** [comment]
Hello, I'm very sorry, but I didn't manage to access the uploaded fern_water dataset in time. It seems that the link has expired. Could you please re-upload it?

**Comment by deborahLevy130** [comment]
Hi, sure! You will find them [here ](https://drive.google.com/file/d/1WMINslKMVQbL7aw7iwoaKlAPLRG_al8Y/view?usp=drive_link)

**Comment by KFClpy** [comment]
Thank you very much
